<Project>
  <PropertyGroup>
    <Authors>wherewhere</Authors>
    <Copyright>Copyright © 2017 - 2026 PavingBase. All Rights Reserved.</Copyright>
    <LangVersion>latest</LangVersion>
    <PackageProjectUrl>https://github.com/Paving-Base/APK-Installer</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Paving-Base/APK-Installer</RepositoryUrl>
  </PropertyGroup>

  <PropertyGroup>
    <AppxAutoIncrementPackageRevision>false</AppxAutoIncrementPackageRevision>
    <AppxBundle>Never</AppxBundle>
    <AppxBundlePlatforms>x86|x64|ARM64</AppxBundlePlatforms>
    <AppxPackageDir>AppPackages</AppxPackageDir>
    <AppxPackageSigningEnabled>false</AppxPackageSigningEnabled>
    <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
    <AppxSymbolPackageEnabled>true</AppxSymbolPackageEnabled>
    <GenerateAppInstallerFile>false</GenerateAppInstallerFile>
    <GenerateTemporaryStoreCertificate>true</GenerateTemporaryStoreCertificate>
    <GenerateTestArtifacts>true</GenerateTestArtifacts>
    <HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
  </PropertyGroup>

  <!-- 
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution 
    Explorer "Package and Publish" context menu entry to be enabled for this project even if 
    the Windows App SDK Nuget package has not yet been restored.
  -->
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>
</Project>
